### ISSUE TITLE
dlq api docs are fixed

### ISSUE THREAD

**Issue by chronark** [DrSh4dow/qstash-rs#1]
re: https://github.com/DrSh4dow/qstash-rs/blob/89dc5a9033b95e076aa5acd781757506894ebf07/src/client/dead_letter_queue.rs#L19

it was not an api bug, but the docs were not up to date, I just updated them.
the endpoint is just `/v2/dlq` and returns messages and optionally a cursor, just like the events

https://upstash.com/docs/qstash/api/dlq/listMessages

**Comment by drsh4dow** [comment]
Hi @chronark,
Thank you for sharing this valuable information and for updating the documentation!

I'll update the respective module ASAP.
